In [1]:
import numpy as np 

In [3]:
mx_1s =np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [9]:
mx_1s = np.ones(5) #for single row and 5 column , ones means all the elements is 1
print(mx_1s)
#out = float type data

[1. 1. 1. 1. 1.]


In [8]:
mx_1s.dtype

dtype('float64')

In [13]:
mx_1s =np.ones((3,4)) #for 3 row and 4 column 
print(mx_1s)
#output = float type data

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
mx_1s = np.ones((3,4),dtype= int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [16]:
mx_0s = np.zeros((4,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [17]:
mx_0s = np.zeros((4,6), dtype = bool) #bool means boolean , in boolean "0"representys the false,thats why false in output
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [18]:
mx_0s = np.zeros((4,6),dtype = str) #str means string , thats why the output contain the string 
print(mx_0s)
#if u convert the "false" and "0" into string then we get the "empty string"

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [19]:
em_str= ''
print(bool(em_str)) # if u convert the empty string into boolean we get the output is "false"

False


In [27]:
em_mx = np.empty((3,7)) 
print(em_mx)
# output may be zero matrix or any thing ,any number 

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 3.00398212e-307
  4.22774898e-307 2.67020916e-307 7.56599807e-307]
 [8.90104239e-307 8.90070286e-308 8.01097889e-307 1.78020169e-306
  7.56601165e-307 1.02359984e-306 1.33510679e-306]
 [2.22522597e-306 1.33511018e-306 6.23057689e-307 1.33511562e-306
  6.89805151e-307 2.56765117e-312 3.91792476e-317]]
