# NumPy functions:

In [1]:
import numpy as np

# arrange()

In [2]:
#np.arange(satrt,end,steps)
ar_1d =np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
even_ar = np.arange(1,13,2)
print(even_ar)

[ 1  3  5  7  9 11]


# linspace()

In [4]:
np.linspace(1,5,4) # "1"and "5"is the range of the output aaray, and "4" tells that there is four number in the output , 
#and the difference of any of two of these fours number in asending order between them gives the constant number 1.33

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()

In [5]:
ar_2d = ar_1d.reshape(2,6) # 2 represent the number of row and , 6 represent the numbwer of column
print(ar_2d)
#in this output we have converted 1dimensional aaray  or 1d into two dimensional aaray 2d
#and the dot product of these two number in the parent thesis is equals to the 12 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
ar_3d = ar_1d.reshape(2,3,2) # 2 represent three dimensional aaray, and 2 represent the two dimensional aaray and ,
#last 2 represent the one dimensional aarray
print(ar_3d)
#and the dot product of the number in the parent thesis is equals to the 12 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()

In [8]:
#ravel convert the multi dimensional aaray into one dimensional aaray
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [9]:
#flatten also converted the multidimensional aaray into one dimensional aaray 
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [10]:
ar.transpose() # here we convert the array "ar" into (6,2) , but the intiallay the aaray "ar" in the form of (2,6)
#where 2 represent the number of row and 6 represent the number of column 

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [11]:
ar.T # we can also use the "T" for the transepose of the matrix

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])