# Mathematices Operation Using NumPy

In [1]:
import numpy as np 

In [3]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)
# create two array in output 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr1 +arr2 #addition of two array with coresspondence place 

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
np.add(arr1,arr2) # we can also use for the adding of the two array

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [6]:
arr1 - arr2 # substraction of the array with correspondece place 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
np.subtract(arr1,arr2)#we can also use the subtaction of the array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
arr1/arr2 # dividation of the two  array 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.divide(arr1, arr2) #we can also use for the division the two array 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
arr1*arr2 # for the multiplcation of the aaray with correspondece place , and the sign of the multiplecation denoted by the "*"
#elementry wise multiplcation have done

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [13]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)
#check the multiply of array which given above 
np.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
np.multiply(arr1 ,arr2) # in this way we can also do the elementry wise multiplication 

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [18]:
arr1@arr2 #its an matrix multiplcation , multiply of row with coulmn , for this type of multuiplication we use the "@"
#or finding the matrix that we do in the engineering mathematics

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [19]:
arr1.dot(arr2) # we can also use the "dot" to do the matrix multiplication 

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [20]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr1.max() # finding the maximum value of the "arr1"

9

In [22]:
arr1.argmax() # finding the index of the "arr1", indexing starts from the zero thats why it tells the indexing 8

8

In [23]:
#for finding the  column maximum value in "arr1"
arr1.max(axis=0) # zero "0" represent the column ,
#in the output we got the maximum value of each column [7,8,9]

array([7, 8, 9])

In [24]:
arr1.max(axis =1) # one "1" represent the row
#In the output we got maximum value of the each row [3,6,9]

array([3, 6, 9])

In [25]:
arr1.min() # finding the minimum value of the "arr1"

1

In [26]:
arr1.argmin() # finding the index of the arr1, indexing starts from the zero 

0

In [29]:
arr1.min(axis=0) # zero represent the column 
#In the output we got the column of the minimum values of the arr1

array([1, 2, 3])

In [30]:
np.sum(arr1) # finding the sum of all the element of "arr1"

45

In [31]:
np.sum(arr1,axis =0) # finding the sum of the each column of the "arr1"

array([12, 15, 18])

In [32]:
np.sum(arr1,axis =1)#finding the sum of the each row of the "arr1"

array([ 6, 15, 24])

In [33]:
arr1 # sum of first column is 12, sum of second column is 15, sum of third column is 18
#similarly sum of first row is 6, sum of second row is 15, sum of third row is 18

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.mean(arr1) # finding the mean of aar1
# sumof all the elemnts of the arr1 is divided by the the number of elements in the arr1

5.0

In [35]:
#finding the square root of the all the element of "arr1"
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [36]:
#finding the standard division the arr1
np.std(arr1)

2.581988897471611

In [37]:
#finding the exponent of all the element of the "arr1"
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [38]:
#finding the  natural log of all the element of the arr1
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [39]:
# finding the log base 10 of all the elements of arr1
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])