# Python NumPy Array  Conctination And Split

In [1]:
import numpy as np

In [5]:
 arr1 =np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [6]:
arr2 = np.arange(17,33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [7]:
#for conctination we cant use the "+" operater
list1 =[2,3,4,5]
list2= [3,5,6,7]
list1 +list2
#output is conctination of two list 

[2, 3, 4, 5, 3, 5, 6, 7]

In [8]:
arr1+arr2 # In this case arrays "arr1"and "arr2" getting add 
#in this case the "=" operater is failed to conctination

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [9]:
np.concatenate((arr1,arr2)) # In this case the conctination is takes place of "arr1" ,  and  "arr2"

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [10]:
print(arr1)
print(arr2)
#for referring the conctination in above 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [11]:
# row wise conctination , means "arr1" first row is conctinate with the "arr2" first row
np.concatenate((arr1,arr2),axis= 1) # for row wise conctination we use "axis=1" , but in the case of column we axis=0, 
#or no need represent "axis=0"

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [12]:
#for column wise conctination we can also use "stack" functions
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [13]:
#for row wise conctination we can also uise "stack" functions
np.hstack((arr1,arr2))
#output is the row wise conctination     

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [14]:
#conctination of more than two arrays
np.hstack((arr1,arr2,arr1,arr2))
#output is conctination is given below

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16, 29, 30, 31, 32]])

In [20]:
# for break the we use the split function
list1 =np.split(arr1,2)
print(list1)
#we have beaark the array into two part row wise with a pair of two row

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [21]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [17]:
list1 = np.split(arr1,2) # checking the "type"
type(list1) # mtlb jo "list1" variable hai usme list type ka data hai aur list jo element hai usme numpy array

list

In [22]:
list1[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
type(list1[0]) # it means iss list me jo zeroth number jo item hai uska data type "ndarray"
#whwn we use split type function,  split fuction split the array ,but it store in "list"

numpy.ndarray

In [27]:
#row wise split 
np.split(arr1,2 ,axis=1) # for row wise we use"axis=1", and  number "2"indicates the number of parts in which array will split 

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [28]:
d1=np.array([4,7,1,3,9]) # split into multiple array
#our first array have value  before index 1
#our second array have value before index 3
# and remaining value in third array 
np.split(d1,[1,3])
#output have 4 at zero index
#and [7,1] is at before 3 index 
#and remaing [3,9]in third array
#and thi

[array([4]), array([7, 1]), array([3, 9])]