# Python NumPy Tutorial : 9

# Random Sampling With NumPy 

In [1]:
import numpy as np
import random 
# we use the random function in the otp generation 

In [2]:
np.random.random(1) #whwn we use the "random" function the value is in between 0 to 1 always

array([0.29966559])

In [3]:
np.random.random((3,3)) #there we get the 2d array , in which there is an 3 row and 3 column is available , and the value of 
#elemnts is lies between "1" to "0"

array([[0.67175993, 0.98120554, 0.8124554 ],
       [0.25925762, 0.47223431, 0.37650466],
       [0.97922544, 0.49838728, 0.92736577]])

In [4]:
np.random.randint(1,4) # here we get the  random number between "1" to "4"

1

In [5]:
np.random.randint(1,4,(4,4)) # 2d array created in the form of array and the element of the array is lies between (1,4)

array([[1, 2, 3, 3],
       [2, 3, 3, 1],
       [2, 3, 1, 2],
       [3, 2, 2, 1]])

In [6]:
np.random.randint(1,4,(3,4,4)) # 3d array is created in the output of the cell , and the element is lies between the (1,4)
#(3,4,4) where 3 indicates number of matrix , and (4,4) indicates the 4 row and 4 column this is used for the 
#understanding of 3d array
#randint gives values which change time to time , when we run the cell again and again the
#the values are change

array([[[2, 1, 3, 2],
        [1, 2, 3, 2],
        [2, 1, 3, 2],
        [3, 3, 3, 3]],

       [[3, 1, 3, 1],
        [2, 1, 2, 3],
        [3, 2, 3, 1],
        [3, 3, 2, 2]],

       [[3, 2, 2, 2],
        [2, 3, 1, 3],
        [2, 1, 1, 1],
        [1, 2, 2, 1]]])

In [7]:
np.random.seed(10)
np.random.randint(1,4,(3,4,4))
#seed(10) gives the same output in output cell every time when we use 
#which shown in the below cell

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]],

       [[2, 2, 2, 3],
        [2, 1, 3, 3],
        [3, 2, 1, 2],
        [2, 1, 3, 2]]])

In [8]:
np.random.seed(10)
np.random.randint(1,4,(3,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]],

       [[2, 2, 2, 3],
        [2, 1, 3, 3],
        [3, 2, 1, 2],
        [2, 1, 3, 2]]])

In [9]:
2**32 -1 #output represent the number of pattern through which we can generate the random value 

4294967295

In [11]:
np.random.rand(5) # we get output with random three numbers in array which shown in output 

array([0.8052232 , 0.52164715, 0.90864888, 0.31923609, 0.09045935])

In [12]:
np.random.rand(5)

array([0.30070006, 0.11398436, 0.82868133, 0.04689632, 0.62628715])

In [13]:
np.random.rand(5,5) # we have created random array with 5 row and 5 column 

array([[0.54758616, 0.819287  , 0.19894754, 0.8568503 , 0.35165264],
       [0.75464769, 0.29596171, 0.88393648, 0.32551164, 0.1650159 ],
       [0.39252924, 0.09346037, 0.82110566, 0.15115202, 0.38411445],
       [0.94426071, 0.98762547, 0.45630455, 0.82612284, 0.25137413],
       [0.59737165, 0.90283176, 0.53455795, 0.59020136, 0.03928177]])

In [15]:
np.random.rand(5,5) # output is different from the above one because its random

array([[0.35718176, 0.07961309, 0.30545992, 0.33071931, 0.7738303 ],
       [0.03995921, 0.42949218, 0.31492687, 0.63649114, 0.34634715],
       [0.04309736, 0.87991517, 0.76324059, 0.87809664, 0.41750914],
       [0.60557756, 0.51346663, 0.59783665, 0.26221566, 0.30087131],
       [0.02539978, 0.30306256, 0.24207588, 0.55757819, 0.56550702]])

In [16]:
x= [1,2,3,4]
np.random.choice(x)

3

In [17]:
np.random.choice(x)

3

In [18]:
np.random.choice(x)

3

In [21]:
for i in range(20):
    print(np.random.choice(x))


2
3
4
1
2
2
2
4
2
4
3
2
4
2
2
4
4
1
1
2


In [22]:
x

[1, 2, 3, 4]

In [23]:
np.random.permutation(x)

array([3, 4, 1, 2])

In [24]:
np.random.permutation(x)

array([1, 2, 3, 4])

In [25]:
np.random.permutation(x)

array([3, 4, 2, 1])

In [26]:
np.random.permutation(x)

array([3, 4, 2, 1])

In [27]:
np.random.permutation(x)

array([1, 3, 2, 4])